-- Populate Staff Data in Tutors Table
-- Generated by: scripts/match-staff-data-tutors.py
-- Date: 2026-04-05 17:08:51
--
-- This migration updates username, student_id, and role fields for 59 matched tutors
-- Tutors matched by tutor_name (abbreviated) from Staff.xlsx
--
-- IMPORTANT: Run 20260405170000_add_staff_columns_to_tutors.sql FIRST
--            to add the username, student_id, and role columns
--
-- Position Mapping:
--   Lead Tutor → lead_tutor
--   Student Manager → manager
--   Student Sysadmin & Project Manager → admin
--   All other positions → tutor
--

-- Total tutors to update: 59
-- Role breakdown: {'tutor': 42, 'lead_tutor': 13, 'manager': 3, 'admin': 1}


-- ============================================
-- Update ADMIN role (1 people)
-- ============================================

-- Emily Koss (Student Sysadmin & Project Manager)
UPDATE tutors
SET username = 'koss001',
    student_id = '3176413',
    role = 'admin'
WHERE tutor_name = 'Emily K.';


-- ============================================
-- Update MANAGER role (3 people)
-- ============================================

-- Elizabeth Hale (Student Manager)
UPDATE tutors
SET username = 'hale007',
    student_id = '3185060',
    role = 'manager'
WHERE tutor_name = 'Elizabeth H.';

-- Van Phan (Student Manager)
UPDATE tutors
SET username = 'phan016',
    student_id = '3179612',
    role = 'manager'
WHERE tutor_name = 'Van P.';

-- Lili Újfalvi (Student Manager)
UPDATE tutors
SET username = 'ujfalvi001',
    student_id = '3166071',
    role = 'manager'
WHERE tutor_name = 'Lili Ú.';


-- ============================================
-- Update LEAD_TUTOR role (13 people)
-- ============================================

-- Kensy Anjeh Akem (Lead Tutor)
UPDATE tutors
SET username = 'anjeh001',
    student_id = '3211062',
    role = 'lead_tutor'
WHERE tutor_name = 'Kensy A.';

-- Alix Daniela Aquino Rivas (Lead Tutor)
UPDATE tutors
SET username = 'aquinori001',
    student_id = '3218415',
    role = 'lead_tutor'
WHERE tutor_name = 'Alix A.';

-- Pedro Aragon (Lead Tutor)
UPDATE tutors
SET username = 'aragonro001',
    student_id = '3198784',
    role = 'lead_tutor'
WHERE tutor_name = 'Pedro A.';

-- Aizirek S. Asylbekova (Lead Tutor)
UPDATE tutors
SET username = 'asylbeko001',
    student_id = '3191963',
    role = 'lead_tutor'
WHERE tutor_name = 'Aizirek A.';

-- Clara Bourke Hurtado (Lead Tutor)
UPDATE tutors
SET username = 'bourkehu001',
    student_id = '3192052',
    role = 'lead_tutor'
WHERE tutor_name = 'Clara B.';

-- Maddy Endler (Lead Tutor)
UPDATE tutors
SET username = 'endler001',
    student_id = '3162109',
    role = 'lead_tutor'
WHERE tutor_name = 'Maddy E.';

-- Lilly Mahle (Lead Tutor)
UPDATE tutors
SET username = 'mahle006',
    student_id = '3204203',
    role = 'lead_tutor'
WHERE tutor_name = 'Lilly M.';

-- Vu Tra My Nguyen (Lead Tutor)
UPDATE tutors
SET username = 'nguyen049',
    student_id = '3170014',
    role = 'lead_tutor'
WHERE tutor_name = 'My N.';

-- Claudia Orte Blanch (Lead Tutor)
UPDATE tutors
SET username = 'orteblan001',
    student_id = '3214156',
    role = 'lead_tutor'
WHERE tutor_name = 'Claudia O.';

-- Eva Sledge (Lead Tutor)
UPDATE tutors
SET username = 'sledge002',
    student_id = '3181507',
    role = 'lead_tutor'
WHERE tutor_name = 'Eva S.';

-- Thuy Phuong Tran (Lead Tutor)
UPDATE tutors
SET username = 'tran024',
    student_id = '3191310',
    role = 'lead_tutor'
WHERE tutor_name = 'Phuong T.';

-- Ethan Weigel (Lead Tutor)
UPDATE tutors
SET username = 'weigel004',
    student_id = '3203131',
    role = 'lead_tutor'
WHERE tutor_name = 'Ethan W.';

-- Isaac Wheeler (Lead Tutor)
UPDATE tutors
SET username = 'wheeler039',
    student_id = '3208532',
    role = 'lead_tutor'
WHERE tutor_name = 'Isaac W.';


-- ============================================
-- Update TUTOR role (42 people)
-- ============================================

-- Clare Caulfield (STEM-PASS Tutor)
UPDATE tutors
SET username = 'caulfiel012',
    student_id = '1722659',
    role = 'tutor'
WHERE tutor_name = 'Clare C';

-- Kayla Cessna (STEM-PASS Tutor)
UPDATE tutors
SET username = 'cessna007',
    student_id = '3182968',
    role = 'tutor'
WHERE tutor_name = 'Kayla C.';

-- Sarah Fulton (STEM-PASS Tutor)
UPDATE tutors
SET username = 'fulton010',
    student_id = '3211848',
    role = 'tutor'
WHERE tutor_name = 'Sarah F.';

-- Nico Huynh (STEM-PASS Tutor)
UPDATE tutors
SET username = 'huynh007',
    student_id = '3132939',
    role = 'tutor'
WHERE tutor_name = 'Nico H.';

-- Gabriel Aloysius Johnson II (STEM-PASS Tutor)
UPDATE tutors
SET username = 'johnsoni001',
    student_id = '3211055',
    role = 'tutor'
WHERE tutor_name = 'Gabriel J.';

-- Princess Mgbemena (STEM-PASS Tutor)
UPDATE tutors
SET username = 'mgbemena001',
    student_id = '3174635',
    role = 'tutor'
WHERE tutor_name = 'Princess M.';

-- Lexi Mobilia (STEM-PASS Tutor)
UPDATE tutors
SET username = 'mobilia006',
    student_id = '3144246',
    role = 'tutor'
WHERE tutor_name = 'Lexi M.';

-- Katrina Orange (STEM-PASS Tutor)
UPDATE tutors
SET username = 'orange002',
    student_id = '3162347',
    role = 'tutor'
WHERE tutor_name = 'Katrina O.';

-- Jocelyn Sawicki (STEM-PASS Tutor)
UPDATE tutors
SET username = 'sawicki001',
    student_id = '3206908',
    role = 'tutor'
WHERE tutor_name = 'Jocelyn S.';

-- Moira Stanisch (STEM-PASS Tutor)
UPDATE tutors
SET username = 'stanisch001',
    student_id = '3147525',
    role = 'tutor'
WHERE tutor_name = 'Moira S.';

-- Claire Stolz (STEM-PASS Tutor)
UPDATE tutors
SET username = 'stolz007',
    student_id = '3208155',
    role = 'tutor'
WHERE tutor_name = 'Claire S.';

-- Abigail Trainor (STEM-PASS Tutor)
UPDATE tutors
SET username = 'trainor003',
    student_id = '3181650',
    role = 'tutor'
WHERE tutor_name = 'Abigail T.';

-- Victoria Wheeler (STEM-PASS Tutor)
UPDATE tutors
SET username = 'wheeler037',
    student_id = '3176247',
    role = 'tutor'
WHERE tutor_name = 'Victoria W.';

-- Preshna karki (STEM-PASS Tutor (SEECS Funded))
UPDATE tutors
SET username = 'karki005',
    student_id = '3159596',
    role = 'tutor'
WHERE tutor_name = 'Preshna K.';

-- Chloe Kitagawa (STEM-PASS Tutor (SEECS Funded))
UPDATE tutors
SET username = 'kitagawa001',
    student_id = '3166609',
    role = 'tutor'
WHERE tutor_name = 'Chloe K.';

-- Javier Mesa Mendez (STEM-PASS Tutor (SEECS Funded))
UPDATE tutors
SET username = 'mesamend001',
    student_id = '3193066',
    role = 'tutor'
WHERE tutor_name = 'Javier M.';

-- Kirsten Slinkard (STEM-PASS Tutor (SEECS Funded))
UPDATE tutors
SET username = 'slinkard001',
    student_id = '3176162',
    role = 'tutor'
WHERE tutor_name = 'Kristen S.';

-- Zaid Abdelkarim Jamil Abbadi (STEMBassador)
UPDATE tutors
SET username = 'abbadi001',
    student_id = '3219698',
    role = 'tutor'
WHERE tutor_name = 'Zaid A.';

-- Ojus Dalvi (TBD)
UPDATE tutors
SET username = 'dalvi002',
    student_id = '3094955',
    role = 'tutor'
WHERE tutor_name = 'Ojus D.';

-- Zoë Gaetjens (TBD)
UPDATE tutors
SET username = 'gaetjens001',
    student_id = '3160847',
    role = 'tutor'
WHERE tutor_name = 'Zoë G.';

-- Phuc Khang Mai (Tech Evangelist)
UPDATE tutors
SET username = 'mai005',
    student_id = '3156592',
    role = 'tutor'
WHERE tutor_name = 'Khang M.';

-- Avish Maniar (Tech Evangelist)
UPDATE tutors
SET username = 'maniar001',
    student_id = '3198602',
    role = 'tutor'
WHERE tutor_name = 'Avish M.';

-- Prashriti Acharya (Tutor)
UPDATE tutors
SET username = 'acharya023',
    student_id = '3165884',
    role = 'tutor'
WHERE tutor_name = 'Prashriti A.';

-- Blossom Anolue (Tutor)
UPDATE tutors
SET username = 'anolue001',
    student_id = '3161501',
    role = 'tutor'
WHERE tutor_name = 'Blossom A.';

-- Kara Bridge (Tutor)
UPDATE tutors
SET username = 'bridge009',
    student_id = '3178489',
    role = 'tutor'
WHERE tutor_name = 'Kara B.';

-- Camryn Brown (Tutor)
UPDATE tutors
SET username = 'brown555',
    student_id = '3179295',
    role = 'tutor'
WHERE tutor_name = 'Camryn B.';

-- Ryan Ehmann (Tutor)
UPDATE tutors
SET username = 'ehmann001',
    student_id = '3181706',
    role = 'tutor'
WHERE tutor_name = 'Ryan E.';

-- Isabella Gingras (Tutor)
UPDATE tutors
SET username = 'gingras002',
    student_id = '3179843',
    role = 'tutor'
WHERE tutor_name = 'Izzy G.';

-- Jonathan Hansford (Tutor)
UPDATE tutors
SET username = 'hansford001',
    student_id = '3202307',
    role = 'tutor'
WHERE tutor_name = 'Jonathan H.';

-- Bailey Hebert (Tutor)
UPDATE tutors
SET username = 'hebert005',
    student_id = '3214420',
    role = 'tutor'
WHERE tutor_name = 'Bailey H.';

-- Natalie Holden (Tutor)
UPDATE tutors
SET username = 'holden007',
    student_id = '3207819',
    role = 'tutor'
WHERE tutor_name = 'Natalie H.';

-- Khanh Le (Tutor)
UPDATE tutors
SET username = 'le020',
    student_id = '3187462',
    role = 'tutor'
WHERE tutor_name = 'Khanh L.';

-- Makayla Lynard (Tutor)
UPDATE tutors
SET username = 'lynard001',
    student_id = '3173946',
    role = 'tutor'
WHERE tutor_name = 'Makayla L.';

-- Rajih Rajiaet Mpanga (Tutor)
UPDATE tutors
SET username = 'mpanga001',
    student_id = '3204917',
    role = 'tutor'
WHERE tutor_name = 'Rajih M.';

-- Glory Ngako (Tutor)
UPDATE tutors
SET username = 'ngako002',
    student_id = '3160440',
    role = 'tutor'
WHERE tutor_name = 'Glory N.';

-- Hiver Ngoma (Tutor)
UPDATE tutors
SET username = 'ngoma001',
    student_id = '3205645',
    role = 'tutor'
WHERE tutor_name = 'Hiver N.';

-- Quoc Bao Ngoc Nguyen (Tutor)
UPDATE tutors
SET username = 'nguyen067',
    student_id = '3188016',
    role = 'tutor'
WHERE tutor_name = 'Quoc N.';

-- Hannah Popovich (Tutor)
UPDATE tutors
SET username = 'popovich011',
    student_id = '3137173',
    role = 'tutor'
WHERE tutor_name = 'Hannah P.';

-- Grady Smith (Tutor)
UPDATE tutors
SET username = 'smith430',
    student_id = '3174095',
    role = 'tutor'
WHERE tutor_name = 'Grady S.';

-- Robert Anthony Tang (Tutor)
UPDATE tutors
SET username = 'tang006',
    student_id = '3205333',
    role = 'tutor'
WHERE tutor_name = 'Robert T.';

-- Hope Tadiwa Tele (Tutor)
UPDATE tutors
SET username = 'tele001',
    student_id = '3207634',
    role = 'tutor'
WHERE tutor_name = 'Hope T.';

-- Kayla Tozier (Tutor)
UPDATE tutors
SET username = 'tozier001',
    student_id = '3135137',
    role = 'tutor'
WHERE tutor_name = 'Kayla T.';


-- ============================================
-- Summary
-- ============================================
-- Total updates: 59
-- Admin: 1
-- Manager: 3
-- Lead Tutor: 13
-- Tutor: 42

-- Verification query
-- Run this after migration to verify updates:
-- SELECT tutor_name, username, student_id, role FROM tutors WHERE username IS NOT NULL ORDER BY role, tutor_name;
