-- Sync Staff Data from Excel to Supabase Users Table
-- Generated by: scripts/match-staff-data.py
-- Date: 2026-04-05 16:57:21
--
-- This migration updates username and role fields for 51 matched tutors
-- Tutors matched by email from Staff.xlsx to existing Supabase tutors table
--
-- Position Mapping:
--   Lead Tutor → lead_tutor (14 people)
--   Student Manager → manager (3 people)
--   Student Sysadmin & Project Manager → admin (1 person)
--   All other positions → tutor (33 people)
--

-- Total tutors to update: 59
-- Role breakdown: {'tutor': 42, 'lead_tutor': 13, 'manager': 3, 'admin': 1}


-- ============================================
-- Update ADMIN role (1 people)
-- ============================================

-- Emily Koss (Student Sysadmin & Project Manager)
UPDATE users
SET role = 'admin',
    updated_at = NOW()
WHERE email = 'koss001@gannon.edu'
  OR email ILIKE '%koss001%';


-- ============================================
-- Update MANAGER role (3 people)
-- ============================================

-- Elizabeth Hale (Student Manager)
UPDATE users
SET role = 'manager',
    updated_at = NOW()
WHERE email = 'hale007@gannon.edu'
  OR email ILIKE '%hale007%';

-- Van Phan (Student Manager)
UPDATE users
SET role = 'manager',
    updated_at = NOW()
WHERE email = 'phan016@gannon.edu'
  OR email ILIKE '%phan016%';

-- Lili Újfalvi (Student Manager)
UPDATE users
SET role = 'manager',
    updated_at = NOW()
WHERE email = 'ujfalvi001@gannon.edu'
  OR email ILIKE '%ujfalvi001%';


-- ============================================
-- Update LEAD_TUTOR role (13 people)
-- ============================================

-- Kensy Anjeh Akem (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'anjeh001@gannon.edu'
  OR email ILIKE '%anjeh001%';

-- Alix Daniela Aquino Rivas (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'aquinori001@gannon.edu'
  OR email ILIKE '%aquinori001%';

-- Pedro Aragon (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'aragonro001@gannon.edu'
  OR email ILIKE '%aragonro001%';

-- Aizirek S. Asylbekova (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'asylbeko001@gannon.edu'
  OR email ILIKE '%asylbeko001%';

-- Clara Bourke Hurtado (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'bourkehu001@gannon.edu'
  OR email ILIKE '%bourkehu001%';

-- Maddy Endler (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'endler001@gannon.edu'
  OR email ILIKE '%endler001%';

-- Lilly Mahle (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'mahle006@gannon.edu'
  OR email ILIKE '%mahle006%';

-- Vu Tra My Nguyen (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'nguyen049@gannon.edu'
  OR email ILIKE '%nguyen049%';

-- Claudia Orte Blanch (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'orteblan001@gannon.edu'
  OR email ILIKE '%orteblan001%';

-- Eva Sledge (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'sledge002@gannon.edu'
  OR email ILIKE '%sledge002%';

-- Thuy Phuong Tran (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'tran024@gannon.edu'
  OR email ILIKE '%tran024%';

-- Ethan Weigel (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'weigel004@gannon.edu'
  OR email ILIKE '%weigel004%';

-- Isaac Wheeler (Lead Tutor)
UPDATE users
SET role = 'lead_tutor',
    updated_at = NOW()
WHERE email = 'wheeler039@gannon.edu'
  OR email ILIKE '%wheeler039%';


-- ============================================
-- Update TUTOR role (42 people)
-- ============================================

-- Clare Caulfield (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'caulfiel012@gannon.edu'
  OR email ILIKE '%caulfiel012%';

-- Kayla Cessna (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'cessna007@gannon.edu'
  OR email ILIKE '%cessna007%';

-- Sarah Fulton (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'fulton010@gannon.edu'
  OR email ILIKE '%fulton010%';

-- Nico Huynh (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'huynh007@gannon.edu'
  OR email ILIKE '%huynh007%';

-- Gabriel Aloysius Johnson II (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'johnsoni001@gannon.edu'
  OR email ILIKE '%johnsoni001%';

-- Princess Mgbemena (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'mgbemena001@gannon.edu'
  OR email ILIKE '%mgbemena001%';

-- Lexi Mobilia (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'mobilia006@gannon.edu'
  OR email ILIKE '%mobilia006%';

-- Katrina Orange (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'orange002@gannon.edu'
  OR email ILIKE '%orange002%';

-- Jocelyn Sawicki (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'sawicki001@gannon.edu'
  OR email ILIKE '%sawicki001%';

-- Moira Stanisch (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'stanisch001@gannon.edu'
  OR email ILIKE '%stanisch001%';

-- Claire Stolz (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'stolz007@gannon.edu'
  OR email ILIKE '%stolz007%';

-- Abigail Trainor (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'trainor003@gannon.edu'
  OR email ILIKE '%trainor003%';

-- Victoria Wheeler (STEM-PASS Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'wheeler037@gannon.edu'
  OR email ILIKE '%wheeler037%';

-- Preshna karki (STEM-PASS Tutor (SEECS Funded))
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'karki005@gannon.edu'
  OR email ILIKE '%karki005%';

-- Chloe Kitagawa (STEM-PASS Tutor (SEECS Funded))
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'kitagawa001@gannon.edu'
  OR email ILIKE '%kitagawa001%';

-- Javier Mesa Mendez (STEM-PASS Tutor (SEECS Funded))
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'mesamend001@gannon.edu'
  OR email ILIKE '%mesamend001%';

-- Kirsten Slinkard (STEM-PASS Tutor (SEECS Funded))
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'slinkard001@gannon.edu'
  OR email ILIKE '%slinkard001%';

-- Zaid Abdelkarim Jamil Abbadi (STEMBassador)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'abbadi001@gannon.edu'
  OR email ILIKE '%abbadi001%';

-- Ojus Dalvi (TBD)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'dalvi002@gannon.edu'
  OR email ILIKE '%dalvi002%';

-- Zoë Gaetjens (TBD)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'gaetjens001@gannon.edu'
  OR email ILIKE '%gaetjens001%';

-- Phuc Khang Mai (Tech Evangelist)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'mai005@gannon.edu'
  OR email ILIKE '%mai005%';

-- Avish Maniar (Tech Evangelist)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'maniar001@gannon.edu'
  OR email ILIKE '%maniar001%';

-- Prashriti Acharya (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'acharya023@gannon.edu'
  OR email ILIKE '%acharya023%';

-- Blossom Anolue (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'anolue001@gannon.edu'
  OR email ILIKE '%anolue001%';

-- Kara Bridge (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'bridge009@gannon.edu'
  OR email ILIKE '%bridge009%';

-- Camryn Brown (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'brown555@gannon.edu'
  OR email ILIKE '%brown555%';

-- Ryan Ehmann (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'ehmann001@gannon.edu'
  OR email ILIKE '%ehmann001%';

-- Isabella Gingras (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'gingras002@gannon.edu'
  OR email ILIKE '%gingras002%';

-- Jonathan Hansford (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'hansford001@gannon.edu'
  OR email ILIKE '%hansford001%';

-- Bailey Hebert (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'hebert005@gannon.edu'
  OR email ILIKE '%hebert005%';

-- Natalie Holden (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'holden007@gannon.edu'
  OR email ILIKE '%holden007%';

-- Khanh Le (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'le020@gannon.edu'
  OR email ILIKE '%le020%';

-- Makayla Lynard (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'lynard001@gannon.edu'
  OR email ILIKE '%lynard001%';

-- Rajih Rajiaet Mpanga (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'mpanga001@gannon.edu'
  OR email ILIKE '%mpanga001%';

-- Glory Ngako (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'ngako002@gannon.edu'
  OR email ILIKE '%ngako002%';

-- Hiver Ngoma (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'ngoma001@gannon.edu'
  OR email ILIKE '%ngoma001%';

-- Quoc Bao Ngoc Nguyen (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'nguyen067@gannon.edu'
  OR email ILIKE '%nguyen067%';

-- Hannah Popovich (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'popovich011@gannon.edu'
  OR email ILIKE '%popovich011%';

-- Grady Smith (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'smith430@gannon.edu'
  OR email ILIKE '%smith430%';

-- Robert Anthony Tang (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'tang006@gannon.edu'
  OR email ILIKE '%tang006%';

-- Hope Tadiwa Tele (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'tele001@gannon.edu'
  OR email ILIKE '%tele001%';

-- Kayla Tozier (Tutor)
UPDATE users
SET role = 'tutor',
    updated_at = NOW()
WHERE email = 'tozier001@gannon.edu'
  OR email ILIKE '%tozier001%';


-- ============================================
-- Summary
-- ============================================
-- Total updates: 59
-- Admin: 1
-- Manager: 3
-- Lead Tutor: 13
-- Tutor: 42
