-- GU faculty seed (generated by scripts/seed-gu-academics.js)
-- Run migration-gu-faculty.sql first if faculty table does not exist.
INSERT INTO faculty (name, department, user_id)
VALUES
  ('Nogaj Adam', 'Library', 'NOGAJ001'),
  ('Adams Heather', 'Physician Assistant Program', 'ADAMS051')
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  department = EXCLUDED.department,
  updated_at = NOW();
