-- Seed Course/Focus Options for Scheduling Page
-- This script adds all course and focus options to the courses table
-- Run this in Supabase SQL Editor

-- Insert all course/focus options
-- Note: course_code is UNIQUE, so entries with same code but different instructors will have NULL course_code
-- The full focus text is stored in course_name for display in the dropdown

INSERT INTO courses (course_code, course_name, active)
VALUES
  -- ACCT courses
  ('ACCT305', 'ACCT305 Intermediate Fin Accounting I - Dr Renee Castrigano Only', true),
  (NULL, 'ACCT305 Intermediate Fin Accounting I - any instructors Only', true),
  ('ACCT313', 'ACCT313 Accounting Information Systems - Mr Blase Nicolia Only', true),
  (NULL, 'ACCT313 Accounting Information Systems - any instructors Only', true),
  ('ACCT315', 'ACCT315 Intermediate Fin Accounting II - Dr Renee Castrigano Only', true),
  (NULL, 'ACCT315 Intermediate Fin Accounting II - any instructors Only', true),
  ('ACCT320', 'ACCT320 Cost Management - Mr Blase Nicolia Only', true),
  (NULL, 'ACCT320 Cost Management - any instructors Only', true),
  ('ACCT415', 'ACCT415 Adv Financial Acct - Dr Renee Castrigano Only', true),
  (NULL, 'ACCT415 Adv Financial Acct - any instructors Only', true),
  ('ACCT440', 'ACCT440 Financial Auditing - Mr Blase Nicolia Only', true),
  (NULL, 'ACCT440 Financial Auditing - any instructors Only', true),
  
  -- Academic/General
  (NULL, 'Academic AdviceMentoring Not Major-Dependent Only', true),
  
  -- BCOR courses
  ('BCOR105', 'BCOR105 Found of Busn Enterprise - Dr Eric Brownlee Only', true),
  (NULL, 'BCOR105 Found of Busn Enterprise - Dr Jinhee Yoo Only', true),
  (NULL, 'BCOR105 Found of Busn Enterprise - Dr Michael Messina Only', true),
  (NULL, 'BCOR105 Found of Busn Enterprise - Dr William McAndrew Only', true),
  (NULL, 'BCOR105 Found of Busn Enterprise - Mr Bruce Kibler Only', true),
  (NULL, 'BCOR105 Found of Busn Enterprise - any instructors Only', true),
  ('BCOR111', 'BCOR111 Prin Microecomonics - Dr M Roth Only', true),
  (NULL, 'BCOR111 Prin Microecomonics - Dr Philip Szmedra Only', true),
  (NULL, 'BCOR111 Prin Microecomonics - any instructors Only', true),
  ('BCOR112', 'BCOR112 Prin Macroeconomics - Dr Philip Szmedra Only', true),
  (NULL, 'BCOR112 Prin Macroeconomics - Dr William McAndrew Only', true),
  (NULL, 'BCOR112 Prin Macroeconomics - Mr John Stone Only', true),
  (NULL, 'BCOR112 Prin Macroeconomics - any instructors Only', true),
  ('BCOR214', 'BCOR214 Prin of Accounting I - Dr Joseph Kuvshinikov Only', true),
  (NULL, 'BCOR214 Prin of Accounting I - Dr Renee Castrigano Only', true),
  (NULL, 'BCOR214 Prin of Accounting I - Mr Blase Nicolia Only', true),
  (NULL, 'BCOR214 Prin of Accounting I - Mr Terry Holmes Only', true),
  (NULL, 'BCOR214 Prin of Accounting I - any instructors Only', true),
  ('BCOR215', 'BCOR215 Prin of Accounting II - Dr Renee Castrigano Only', true),
  (NULL, 'BCOR215 Prin of Accounting II - Mr Blase Nicolia Only', true),
  (NULL, 'BCOR215 Prin of Accounting II - Mr Terry Holmes Only', true),
  (NULL, 'BCOR215 Prin of Accounting II - any instructors Only', true),
  ('BCOR220', 'BCOR220 Intro to Statistical Analysis - Dr Celene Kalivoda Only', true),
  (NULL, 'BCOR220 Intro to Statistical Analysis - Dr Keith Holler Only', true),
  (NULL, 'BCOR220 Intro to Statistical Analysis - Dr Xiangjing Wei Only', true),
  (NULL, 'BCOR220 Intro to Statistical Analysis - any instructors Only', true),
  ('BCOR240', 'BCOR240 Marketing in Global Env - Dr Michael Messina Only', true),
  (NULL, 'BCOR240 Marketing in Global Env - any instructors Only', true),
  ('BCOR241', 'BCOR241 Prin of Marketing - Dr Michael Messina Only', true),
  (NULL, 'BCOR241 Prin of Marketing - any instructors Only', true),
  ('BCOR250', 'BCOR250 Mgmt Theory and Practice - Dr Earl Brieger Only', true),
  (NULL, 'BCOR250 Mgmt Theory and Practice - Dr Eric Brownlee Only', true),
  (NULL, 'BCOR250 Mgmt Theory and Practice - Dr Joseph Kuvshinikov Only', true),
  (NULL, 'BCOR250 Mgmt Theory and Practice - Mr Kurt Hersch Only', true),
  (NULL, 'BCOR250 Mgmt Theory and Practice - Mr Thomas Comstock Only', true),
  (NULL, 'BCOR250 Mgmt Theory and Practice - any instructors Only', true),
  ('BCOR303', 'BCOR303 Legal Env of Business - Mr Terry Holmes Only', true),
  (NULL, 'BCOR303 Legal Env of Business - any instructors Only', true),
  ('BCOR311', 'BCOR311 Financial Mgt 1 - Dr Lei Wang Only', true),
  (NULL, 'BCOR311 Financial Mgt 1 - any instructors Only', true),
  (NULL, 'BCOR311 Financial Mgt 1 Financial Mgt 1 - Dr Lei Wang Only', true),
  (NULL, 'BCOR311 Financial Mgt 1 Financial Mgt 1 - Mr John Stone Only', true),
  (NULL, 'BCOR311 Financial Mgt 1 Financial Mgt 1 - any instructors Only', true),
  ('BCOR440', 'BCOR440 Operations  Supply Chain Mgmt - Dr Celene Kalivoda Only', true),
  (NULL, 'BCOR440 Operations  Supply Chain Mgmt - Ms Benyawarath Nithithanatchinnapat Only', true),
  (NULL, 'BCOR440 Operations  Supply Chain Mgmt - any instructors Only', true),
  
  -- BIOL courses
  ('BIOL103', 'BIOL103 Environmental Issues - Dr Steven Ropski Only', true),
  (NULL, 'BIOL103 Environmental Issues - Ms Michelle Kuns Only', true),
  (NULL, 'BIOL103 Environmental Issues - any instructors Only', true),
  ('BIOL104', 'BIOL104 Human Biology - Dr Mary Vagula Only', true),
  (NULL, 'BIOL104 Human Biology - any instructors Only', true),
  ('BIOL106', 'BIOL106 Intro Microbiology - any instructors Only', true),
  (NULL, 'BIOL106 Intro Microbiology Intro Microbiology - Dr Matthew Gacura Only', true),
  (NULL, 'BIOL106 Intro Microbiology Intro Microbiology - any instructors Only', true),
  ('BIOL107', 'BIOL107 Intro Microbiol Lab Intro Microbiol Lab - Dr Matthew Gacura Only', true),
  (NULL, 'BIOL107 Intro Microbiol Lab Intro Microbiol Lab - any instructors Only', true),
  ('BIOL115', 'BIOL115 Hum Anatomy  Phys 1 - Mrs Renee Foradori Only', true),
  (NULL, 'BIOL115 Hum Anatomy  Phys 1 - any instructors Only', true),
  ('BIOL116', 'BIOL116 Hum AnatPhys Lab 1 - Mrs Renee Foradori Only', true),
  (NULL, 'BIOL116 Hum AnatPhys Lab 1 - any instructors Only', true),
  ('BIOL117', 'BIOL117 Hum Anatomy  Phys 2 - Dr Prasad Dalvi Only', true),
  (NULL, 'BIOL117 Hum Anatomy  Phys 2 - Mrs Renee Foradori Only', true),
  (NULL, 'BIOL117 Hum Anatomy  Phys 2 - any instructors Only', true),
  ('BIOL118', 'BIOL118 Hum AnatPhys Lab 2 - Mrs Melanie Gustafson-Ropski Only', true),
  (NULL, 'BIOL118 Hum AnatPhys Lab 2 - Mrs Renee Foradori Only', true),
  (NULL, 'BIOL118 Hum AnatPhys Lab 2 - any instructors Only', true),
  ('BIOL122', 'BIOL122 MolCellular Biology - Dr Gregory Andraso Only', true),
  (NULL, 'BIOL122 MolCellular Biology - Dr He Liu Only', true),
  (NULL, 'BIOL122 MolCellular Biology - Dr Michael Ganger Only', true),
  (NULL, 'BIOL122 MolCellular Biology - Dr Quyen Aoh Only', true),
  (NULL, 'BIOL122 MolCellular Biology - any instructors Only', true),
  ('BIOL123', 'BIOL123 MolCell Biology Lab - Mr Christopher Johns Only', true),
  (NULL, 'BIOL123 MolCell Biology Lab - Ms Michelle Kuns Only', true),
  (NULL, 'BIOL123 MolCell Biology Lab - any instructors Only', true),
  ('BIOL124', 'BIOL124 Animal FormFunction - Dr Elisa Konieczko Only', true),
  (NULL, 'BIOL124 Animal FormFunction - Dr Gregory Andraso Only', true),
  (NULL, 'BIOL124 Animal FormFunction - Dr Michael Ganger Only', true),
  (NULL, 'BIOL124 Animal FormFunction - Dr Quyen Aoh Only', true),
  (NULL, 'BIOL124 Animal FormFunction - Dr Steven Ropski Only', true),
  (NULL, 'BIOL124 Animal FormFunction - any instructors Only', true),
  ('BIOL125', 'BIOL125 Animal FormFunc Lab - Dr Tia Young Only', true),
  (NULL, 'BIOL125 Animal FormFunc Lab - Mrs Melanie Gustafson-Ropski Only', true),
  (NULL, 'BIOL125 Animal FormFunc Lab - Ms Michelle Kuns Only', true),
  (NULL, 'BIOL125 Animal FormFunc Lab - any instructors Only', true),
  ('BIOL126', 'BIOL126 Ecosystem Bio  Evol - Dr Elizabeth George Only', true),
  (NULL, 'BIOL126 Ecosystem Bio  Evol - Dr Michael Ganger Only', true),
  (NULL, 'BIOL126 Ecosystem Bio  Evol - Dr Steven Ropski Only', true),
  (NULL, 'BIOL126 Ecosystem Bio  Evol - any instructors Only', true),
  ('BIOL127', 'BIOL127 Ecosystem Biol  Evol Lab - Dr Elizabeth George Only', true),
  (NULL, 'BIOL127 Ecosystem Biol  Evol Lab - Dr Michael Ganger Only', true),
  (NULL, 'BIOL127 Ecosystem Biol  Evol Lab - Dr Steven Ropski Only', true),
  (NULL, 'BIOL127 Ecosystem Biol  Evol Lab - any instructors Only', true),
  ('BIOL140', 'BIOL140 Intro Aquatic Science - Ms Michelle Kuns Only', true),
  (NULL, 'BIOL140 Intro Aquatic Science - any instructors Only', true),
  ('BIOL220', 'BIOL220 Botany - Dr Michael Ganger Only', true),
  (NULL, 'BIOL220 Botany - any instructors Only', true),
  ('BIOL232', 'BIOL232 Human Genetics - Dr Russell Minton Only', true),
  ('BIOL265', 'BIOL265 Genetics - Dr Quyen Aoh Only', true),
  (NULL, 'BIOL265 Genetics - any instructors Only', true),
  ('BIOL266', 'BIOL266 Genetics Lab - Dr Quyen Aoh Only', true),
  (NULL, 'BIOL266 Genetics Lab - any instructors Only', true),
  ('BIOL298', 'BIOL298 Prin of Ecology - Dr Michael Ganger Only', true),
  (NULL, 'BIOL298 Prin of Ecology - any instructors Only', true),
  ('BIOL299', 'BIOL299 Princpl Ecology Lab - Dr Michael Ganger Only', true),
  (NULL, 'BIOL299 Princpl Ecology Lab - any instructors Only', true),
  (NULL, 'BIOL302 Animal Behavior Animal Behavior - Dr Gregory Andraso Only', true),
  (NULL, 'BIOL302 Animal Behavior Animal Behavior - any instructors Only', true),
  ('BIOL306', 'BIOL306 Oceanography - Dr Christopher Dempsey Only', true),
  (NULL, 'BIOL306 Oceanography - any instructors Only', true),
  (NULL, 'BIOL325 Vertebrate Zoology Vertebrate Zoology - Dr Steven Ropski Only', true),
  (NULL, 'BIOL325 Vertebrate Zoology Vertebrate Zoology - any instructors Only', true),
  (NULL, 'BIOL326 Vertebrate Zoo Lab Vertebrate Zoo Lab - Dr Steven Ropski Only', true),
  (NULL, 'BIOL326 Vertebrate Zoo Lab Vertebrate Zoo Lab - any instructors Only', true),
  ('BIOL331', 'BIOL331 Microbiology - Dr Matthew Gacura Only', true),
  (NULL, 'BIOL331 Microbiology - any instructors Only', true),
  ('BIOL332', 'BIOL332 Microbiology Lab - Dr Matthew Gacura Only', true),
  (NULL, 'BIOL332 Microbiology Lab - any instructors Only', true),
  ('BIOL340', 'BIOL340 Aquatic Microbiology - Dr Matthew Gacura Only', true),
  (NULL, 'BIOL340 Aquatic Microbiology - any instructors Only', true),
  (NULL, 'BIOL341 Aquatic Micro Lab Aquatic Micro Lab - Dr Matthew Gacura Only', true),
  (NULL, 'BIOL341 Aquatic Micro Lab Aquatic Micro Lab - any instructors Only', true),
  ('BIOL365', 'BIOL365 Human Gross Anatomy - Dr Prasad Dalvi Only', true),
  (NULL, 'BIOL365 Human Gross Anatomy - any instructors Only', true),
  ('BIOL366', 'BIOL366 Human Gross Anat Lab - Dr Prasad Dalvi Only', true),
  (NULL, 'BIOL366 Human Gross Anat Lab - any instructors Only', true),
  ('BIOL368', 'BIOL368 Human Physiology - Dr He Liu Only', true),
  (NULL, 'BIOL368 Human Physiology - Dr Mary Vagula Only', true),
  (NULL, 'BIOL368 Human Physiology - any instructors Only', true),
  ('BIOL369', 'BIOL369 Human Physio Lab - Dr He Liu Only', true),
  (NULL, 'BIOL369 Human Physio Lab - Dr Mary Vagula Only', true),
  (NULL, 'BIOL369 Human Physio Lab - any instructors Only', true),
  ('BIOL378', 'BIOL378 Medical Microbiology - Dr Gary Vanderlaan Only', true),
  (NULL, 'BIOL378 Medical Microbiology - any instructors Only', true),
  ('BIOL379', 'BIOL379 Med Micro Lab - Dr Gary Vanderlaan Only', true),
  (NULL, 'BIOL379 Med Micro Lab - any instructors Only', true),
  ('BIOL383', 'BIOL383 Tropical Marine Biol - Dr Christopher Dempsey Only', true),
  (NULL, 'BIOL383 Tropical Marine Biol - Ms Michelle Kuns Only', true),
  (NULL, 'BIOL383 Tropical Marine Biol - any instructors Only', true),
  ('BIOL384', 'BIOL384 Ecolgy Yellwstn Park - Dr Steven Ropski Only', true),
  (NULL, 'BIOL384 Ecolgy Yellwstn Park - any instructors Only', true),
  ('BIOL385', 'BIOL385 Limnology - Dr Christopher Dempsey Only', true),
  (NULL, 'BIOL385 Limnology - any instructors Only', true),
  ('BIOL386', 'BIOL386 Limnology Lab - Dr Christopher Dempsey Only', true),
  (NULL, 'BIOL386 Limnology Lab - any instructors Only', true),
  ('BIOL395', 'BIOL395 Fisheries Biology - Dr Gregory Andraso Only', true),
  (NULL, 'BIOL395 Fisheries Biology - any instructors Only', true),
  ('BIOL396', 'BIOL396 Fisheries Biology Lab - Dr Gregory Andraso Only', true),
  (NULL, 'BIOL396 Fisheries Biology Lab - any instructors Only', true),
  ('BIOL487', 'BIOL487 Directed Research - Dr He Liu Only', true),
  (NULL, 'BIOL487 Directed Research - Dr Matthew Gacura Only', true),
  (NULL, 'BIOL487 Directed Research - Dr Steven Ropski Only', true),
  (NULL, 'BIOL487 Directed Research - any instructors Only', true),
  ('BIOL492', 'BIOL492 Spec Topics in Biol - Mrs Melanie Gustafson-Ropski Only', true),
  (NULL, 'BIOL492 Spec Topics in Biol - any instructors Only', true),
  ('BIOL493', 'BIOL493 Spec Topics in Biol - Dr Steven Ropski Only', true),
  (NULL, 'BIOL493 Spec Topics in Biol - any instructors Only', true),
  
  -- BME courses
  ('BME307', 'BME307 Bioengineering Research Meth - Dr Xiaoxu Ji Only', true),
  (NULL, 'BME307 Bioengineering Research Meth - any instructors Only', true),
  ('BME308', 'BME308 Rsch Proj Clin Biomechanics - Dr Xiaoxu Ji Only', true),
  (NULL, 'BME308 Rsch Proj Clin Biomechanics - any instructors Only', true),
  ('BME310', 'BME310 Biomaterials - Dr Longyan Chen Only', true),
  (NULL, 'BME310 Biomaterials - any instructors Only', true),
  ('BME467', 'BME467 Biofluid Mechanics - Dr Longyan Chen Only', true),
  (NULL, 'BME467 Biofluid Mechanics - any instructors Only', true),
  
  -- CHEM courses
  ('CHEM102', 'CHEM102 Intro Org  Bio Chem - any instructors Only', true),
  ('CHEM103', 'CHEM103 Chemistry of Life 1 - Dr Betty Jo Chitester Only', true),
  (NULL, 'CHEM103 Chemistry of Life 1 - Kevin Burridge Only', true),
  (NULL, 'CHEM103 Chemistry of Life 1 - any instructors Only', true),
  ('CHEM104', 'CHEM104 Chem of Life Lab 1 - Kevin Burridge Only', true),
  (NULL, 'CHEM104 Chem of Life Lab 1 - Mr Shawn Feiock Only', true),
  (NULL, 'CHEM104 Chem of Life Lab 1 - any instructors Only', true),
  ('CHEM105', 'CHEM105 Physiological Chem - Dr Aaron Forbes Only', true),
  (NULL, 'CHEM105 Physiological Chem - Kellie Jircitano Only', true),
  (NULL, 'CHEM105 Physiological Chem - Kevin Burridge Only', true),
  (NULL, 'CHEM105 Physiological Chem - any instructors Only', true),
  ('CHEM106', 'CHEM106 Chemistry of Life 2 - Dr Betty Jo Chitester Only', true),
  (NULL, 'CHEM106 Chemistry of Life 2 - any instructors Only', true),
  ('CHEM107', 'CHEM107 Chem of Life Lab 2 - Kellie Jircitano Only', true),
  (NULL, 'CHEM107 Chem of Life Lab 2 - Mr Shawn Feiock Only', true),
  (NULL, 'CHEM107 Chem of Life Lab 2 - any instructors Only', true),
  ('CHEM108', 'CHEM108 Physiologicl Chem Lab - Dr Aaron Forbes Only', true),
  (NULL, 'CHEM108 Physiologicl Chem Lab - any instructors Only', true),
  ('CHEM111', 'CHEM111 General Chemistry 1 - Dr Matthew Heerboth Only', true),
  (NULL, 'CHEM111 General Chemistry 1 - Dr Weslene Tallmadge Only', true),
  (NULL, 'CHEM111 General Chemistry 1 - Ms Natalie Stano Only', true),
  (NULL, 'CHEM111 General Chemistry 1 - any instructors Only', true),
  (NULL, 'CHEM111 General Chemistry 1 General Chemistry 1 - Dr Keith Krise Only', true),
  (NULL, 'CHEM111 General Chemistry 1 General Chemistry 1 - Dr Matthew Heerboth Only', true),
  (NULL, 'CHEM111 General Chemistry 1 General Chemistry 1 - Dr Weslene Tallmadge Only', true),
  (NULL, 'CHEM111 General Chemistry 1 General Chemistry 1 - Ms Natalie Stano Only', true),
  (NULL, 'CHEM111 General Chemistry 1 General Chemistry 1 - any instructors Only', true),
  ('CHEM112', 'CHEM112 General Chem Lab 1 - Dr Keith Krise Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 - Dr Matthew Heerboth Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 - Kellie Jircitano Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 - Mrs Cynthia Willis Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 - Ms Mary Mullen Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 - Ms Natalie Stano Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 - any instructors Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 General Chem Lab 1 - Dr Keith Krise Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 General Chem Lab 1 - Dr Matthew Heerboth Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 General Chem Lab 1 - Jerry Phelps Only', true),
  (NULL, 'CHEM112 General Chem Lab 1 General Chem Lab 1 - any instructors Only', true),
  ('CHEM114', 'CHEM114 General Chemistry 2 - Dr Matthew Heerboth Only', true),
  (NULL, 'CHEM114 General Chemistry 2 - Dr Weslene Tallmadge Only', true),
  (NULL, 'CHEM114 General Chemistry 2 - Ms Natalie Stano Only', true),
  (NULL, 'CHEM114 General Chemistry 2 - any instructors Only', true),
  (NULL, 'CHEM114 General Chemistry 2 General Chemistry 2 - Dr Matthew Heerboth Only', true),
  (NULL, 'CHEM114 General Chemistry 2 General Chemistry 2 - Ms Natalie Stano Only', true),
  (NULL, 'CHEM114 General Chemistry 2 General Chemistry 2 - any instructors Only', true),
  ('CHEM115', 'CHEM115 General Chem Lab 2 - Dr Keith Krise Only', true),
  (NULL, 'CHEM115 General Chem Lab 2 - Kellie Jircitano Only', true),
  (NULL, 'CHEM115 General Chem Lab 2 - Mrs Cynthia Willis Only', true),
  (NULL, 'CHEM115 General Chem Lab 2 - Ms Natalie Stano Only', true),
  (NULL, 'CHEM115 General Chem Lab 2 - Staff Only', true),
  (NULL, 'CHEM115 General Chem Lab 2 - any instructors Only', true),
  (NULL, 'CHEM115 General Chem Lab 2 General Chem Lab 2 - Kellie Jircitano Only', true),
  (NULL, 'CHEM115 General Chem Lab 2 General Chem Lab 2 - Ms Madison Harrier Only', true),
  (NULL, 'CHEM115 General Chem Lab 2 General Chem Lab 2 - any instructors Only', true),
  ('CHEM221', 'CHEM221 Organic Chem 1 - Dr Christine Saber Only', true),
  (NULL, 'CHEM221 Organic Chem 1 - Dr Ria Betush Only', true),
  (NULL, 'CHEM221 Organic Chem 1 - any instructors Only', true),
  (NULL, 'CHEM221 Organic Chem 1 Organic Chem 1 - Dr Christine Saber Only', true),
  (NULL, 'CHEM221 Organic Chem 1 Organic Chem 1 - Dr Ria Betush Only', true),
  (NULL, 'CHEM221 Organic Chem 1 Organic Chem 1 - any instructors Only', true),
  ('CHEM222', 'CHEM222 Organic Chem Lab 1 - Dr Christine Saber Only', true),
  (NULL, 'CHEM222 Organic Chem Lab 1 - Dr Keith Krise Only', true),
  (NULL, 'CHEM222 Organic Chem Lab 1 - Dr Ria Betush Only', true),
  (NULL, 'CHEM222 Organic Chem Lab 1 - Ms Natalie Stano Only', true),
  (NULL, 'CHEM222 Organic Chem Lab 1 - any instructors Only', true),
  (NULL, 'CHEM222 Organic Chem Lab 1 Organic Chem Lab 1 - Dr Christine Saber Only', true),
  (NULL, 'CHEM222 Organic Chem Lab 1 Organic Chem Lab 1 - Ms Natalie Stano Only', true),
  (NULL, 'CHEM222 Organic Chem Lab 1 Organic Chem Lab 1 - any instructors Only', true),
  ('CHEM224', 'CHEM224 Organic Chem 2 - Dr Christine Saber Only', true),
  (NULL, 'CHEM224 Organic Chem 2 - Dr Ria Betush Only', true),
  (NULL, 'CHEM224 Organic Chem 2 - any instructors Only', true),
  (NULL, 'CHEM224 Organic Chem 2 Organic Chem 2 - Dr Christine Saber Only', true),
  (NULL, 'CHEM224 Organic Chem 2 Organic Chem 2 - Dr Ria Betush Only', true),
  (NULL, 'CHEM224 Organic Chem 2 Organic Chem 2 - any instructors Only', true),
  ('CHEM225', 'CHEM225 Organic Chem Lab 2 - Dr Christine Saber Only', true),
  (NULL, 'CHEM225 Organic Chem Lab 2 - Dr Ria Betush Only', true),
  (NULL, 'CHEM225 Organic Chem Lab 2 - any instructors Only', true),
  (NULL, 'CHEM225 Organic Chem Lab 2 Organic Chem Lab 2 - Dr Aaron Forbes Only', true),
  (NULL, 'CHEM225 Organic Chem Lab 2 Organic Chem Lab 2 - Dr Ria Betush Only', true),
  (NULL, 'CHEM225 Organic Chem Lab 2 Organic Chem Lab 2 - any instructors Only', true),
  ('CHEM325', 'CHEM325 Organic Spectroscop Mthds - Dr Christine Saber Only', true),
  (NULL, 'CHEM325 Organic Spectroscop Mthds - any instructors Only', true),
  ('CHEM326', 'CHEM326 Organic Spectroscopic Methods Lab - Dr Christine Saber Only', true),
  (NULL, 'CHEM326 Organic Spectroscopic Methods Lab - any instructors Only', true),
  ('CHEM331', 'CHEM331 Physical Chemistry 1 - Dr Lisa Nogaj Only', true),
  (NULL, 'CHEM331 Physical Chemistry 1 - any instructors Only', true),
  ('CHEM332', 'CHEM332 Physical Chem Lab 1 - Dr Keith Krise Only', true),
  (NULL, 'CHEM332 Physical Chem Lab 1 - any instructors Only', true),
  (NULL, 'CHEM332 Physical Chem Lab 1 Physical Chem Lab 1 - Dr Keith Krise Only', true),
  (NULL, 'CHEM332 Physical Chem Lab 1 Physical Chem Lab 1 - any instructors Only', true),
  ('CHEM336', 'CHEM336 Modern Analyt Chem - Dr Weslene Tallmadge Only', true),
  (NULL, 'CHEM336 Modern Analyt Chem - any instructors Only', true),
  ('CHEM366', 'CHEM366 Structural Biochem - Dr Betty Jo Chitester Only', true),
  (NULL, 'CHEM366 Structural Biochem - any instructors Only', true),
  (NULL, 'CHEM366 Structural Biochem Structural Biochem - Dr Betty Jo Chitester Only', true),
  (NULL, 'CHEM366 Structural Biochem Structural Biochem - any instructors Only', true),
  ('CHEM367', 'CHEM367 Biochemical Lab - Ms Natalie Stano Only', true),
  (NULL, 'CHEM381 Undergrad Research Undergrad Research - Dr Betty Jo Chitester Only', true),
  (NULL, 'CHEM381 Undergrad Research Undergrad Research - any instructors Only', true),
  
  -- CIS courses
  ('CIS150', 'CIS150 Business Technology 1 - Mr David Marino Only', true),
  (NULL, 'CIS150 Business Technology 1 - Mr Joseph Kwashnak Only', true),
  (NULL, 'CIS150 Business Technology 1 - Mr Michael Beiter Only', true),
  (NULL, 'CIS150 Business Technology 1 - any instructors Only', true),
  ('CIS180', 'CIS180 Prob Solv  Comp Prog - Mr Mark Blair Only', true),
  (NULL, 'CIS180 Prob Solv  Comp Prog - Mr Rashid Khan Only', true),
  (NULL, 'CIS180 Prob Solv  Comp Prog - Ms Marwah Obaid Only', true),
  (NULL, 'CIS180 Prob Solv  Comp Prog - any instructors Only', true),
  ('CIS181', 'CIS181 Prob SolvComPg Lab - Mr Mark Blair Only', true),
  (NULL, 'CIS181 Prob SolvComPg Lab - Mr Rashid Khan Only', true),
  (NULL, 'CIS181 Prob SolvComPg Lab - Ms Marwah Obaid Only', true),
  (NULL, 'CIS181 Prob SolvComPg Lab - any instructors Only', true),
  ('CIS182', 'CIS182 Object Orient Prog - Dr Hector Perez-Gonzalez Only', true),
  (NULL, 'CIS182 Object Orient Prog - any instructors Only', true),
  ('CIS183', 'CIS183 Object Orient Prog Lab - Dr Hector Perez-Gonzalez Only', true),
  (NULL, 'CIS183 Object Orient Prog Lab - Dr Sheheeda Mariam Manakkadu Only', true),
  (NULL, 'CIS183 Object Orient Prog Lab - any instructors Only', true),
  ('CIS219', 'CIS219 Linux Programming - Dr Richard Matovu Only', true),
  (NULL, 'CIS219 Linux Programming - Dr Ronny Bazan-Antequera Only', true),
  (NULL, 'CIS219 Linux Programming - any instructors Only', true),
  ('CIS239', 'CIS239 The User Experience - Mr Brian Camodeca Only', true),
  (NULL, 'CIS239 The User Experience - any instructors Only', true),
  ('CIS240', 'CIS240 Web Management  Design - Mr Uzoma Onwumelu Only', true),
  ('CIS252', 'CIS252 Advanced Excel - Joshua Maurer Only', true),
  (NULL, 'CIS252 Advanced Excel - Mrs Temidayo Osatuyi Only', true),
  (NULL, 'CIS252 Advanced Excel - Ms Benyawarath Nithithanatchinnapat Only', true),
  (NULL, 'CIS252 Advanced Excel - any instructors Only', true),
  ('CIS255', 'CIS255 Database Management and Administration - Dr Kefei Wang Only', true),
  (NULL, 'CIS255 Database Management and Administration - any instructors Only', true),
  ('CIS277', 'CIS277 Mobile Appl Devlp 1 - Mr Jizhou Tong Only', true),
  (NULL, 'CIS277 Mobile Appl Devlp 1 - any instructors Only', true),
  ('CIS287', 'CIS287 Obj-Orient Dsgn Lab - Dr Hector Perez-Gonzalez Only', true),
  ('CIS326', 'CIS326 Frml Meth Sftw Dev - Mr Jizhou Tong Only', true),
  (NULL, 'CIS326 Frml Meth Sftw Dev - any instructors Only', true),
  ('CIS350', 'CIS350 Rqmts  Project Mgmt - Ms Marwah Obaid Only', true),
  (NULL, 'CIS350 Rqmts  Project Mgmt - any instructors Only', true),
  ('CIS355', 'CIS355 Web Programming and Implementation - Mr Jeremy Cannell Only', true),
  (NULL, 'CIS355 Web Programming and Implementation - any instructors Only', true),
  ('CIS387', 'CIS387 System  Network Secur - Dr Ronny Bazan-Antequera Only', true),
  (NULL, 'CIS387 System  Network Secur - any instructors Only', true),
  ('CIS457', 'CIS457 Senior Design 1 - Dr Mei-Huei Tang Only', true),
  (NULL, 'CIS457 Senior Design 1 - any instructors Only', true),
  
  -- DIET courses
  ('DIET202', 'DIET202 Nutrition - Mrs Sally Klinner Only', true),
  (NULL, 'DIET202 Nutrition - Ms Sandra Luthringer Only', true),
  (NULL, 'DIET202 Nutrition - any instructors Only', true),
  (NULL, 'DIET202 Nutrition Nutrition - Ms Sandra Luthringer Only', true),
  (NULL, 'DIET202 Nutrition Nutrition - any instructors Only', true),
  
  -- ECE courses
  ('ECE105', 'ECE105 Engineer Tools Appl - Ms Xin Gao Only', true),
  (NULL, 'ECE105 Engineer Tools Appl - any instructors Only', true),
  ('ECE106', 'ECE106 Engineer Tools Appl Lab - Ms Xin Gao Only', true),
  (NULL, 'ECE106 Engineer Tools Appl Lab - any instructors Only', true),
  ('ECE231', 'ECE231 Intro Elec Engr - Ms Xin Gao Only', true),
  (NULL, 'ECE231 Intro Elec Engr - any instructors Only', true),
  ('ECE232', 'ECE232 Intro Elec Engr Lab - Mr Robert Rodgers Only', true),
  (NULL, 'ECE232 Intro Elec Engr Lab - any instructors Only', true),
  ('ECE337', 'ECE337 Computer Architectur - Dr Yong-Kyu Jung Only', true),
  
  -- ECON courses
  ('ECON441', 'ECON441 International Econ - Dr William McAndrew Only', true),
  (NULL, 'ECON441 International Econ - any instructors Only', true),
  
  -- ENG courses
  ('ENG102', 'ENG102 Intro to Engineering  Computing - Dr Ikechukwu Ohu Only', true),
  (NULL, 'ENG102 Intro to Engineering  Computing - Dr Lin Zhao Only', true),
  (NULL, 'ENG102 Intro to Engineering  Computing - Dr Longfei Zhou Only', true),
  (NULL, 'ENG102 Intro to Engineering  Computing - Dr Longyan Chen Only', true),
  (NULL, 'ENG102 Intro to Engineering  Computing - Dr Varun Kasaraneni Only', true),
  (NULL, 'ENG102 Intro to Engineering  Computing - Staff Only', true),
  (NULL, 'ENG102 Intro to Engineering  Computing - any instructors Only', true),
  ('ENG380', 'ENG380 Professional Seminar - Dr Ikechukwu Ohu Only', true),
  
  -- ENV courses
  ('ENV101', 'ENV101 Physical Geology - Dr David Hoch Only', true),
  (NULL, 'ENV101 Physical Geology - any instructors Only', true),
  ('ENV102', 'ENV102 Physical Geo Lab - Dr David Hoch Only', true),
  (NULL, 'ENV102 Physical Geo Lab - any instructors Only', true),
  ('ENV120', 'ENV120 Principles Env Sci - Dr Liu Cao Only', true),
  (NULL, 'ENV120 Principles Env Sci - Staff Only', true),
  (NULL, 'ENV120 Principles Env Sci - any instructors Only', true),
  ('ENV121', 'ENV121 Princ EnerClimate Chg - Dr Michelle Homan Only', true),
  (NULL, 'ENV121 Princ EnerClimate Chg - any instructors Only', true),
  ('ENV307', 'ENV307 Soil Science - Dr Liu Cao Only', true),
  (NULL, 'ENV307 Soil Science - any instructors Only', true),
  ('ENV383', 'ENV383 Envionmentl Research - Dr Liu Cao Only', true),
  (NULL, 'ENV383 Envionmentl Research - any instructors Only', true),
  ('ENV400', 'ENV400 Environ Toxicology - Dr Liu Cao Only', true),
  (NULL, 'ENV400 Environ Toxicology - any instructors Only', true),
  ('ENV401', 'ENV401 Env Hlth  Tox Lab - Dr Liu Cao Only', true),
  (NULL, 'ENV401 Env Hlth  Tox Lab - any instructors Only', true),
  ('ENV422', 'ENV422 Wetlands Sci  Eng - Mr Joseph Hudson Only', true),
  (NULL, 'ENV422 Wetlands Sci  Eng - any instructors Only', true),
  ('ENV496', 'ENV496 Senior Thesis 1 - Dr Hwidong Kim Only', true),
  (NULL, 'ENV496 Senior Thesis 1 - any instructors Only', true),
  
  -- FINC courses
  ('FINC300', 'FINC300 Intro Risk Mgmt  Ins - Dr Xiangjing Wei Only', true),
  (NULL, 'FINC300 Intro Risk Mgmt  Ins - any instructors Only', true),
  ('FINC310', 'FINC310 Financial Markets and Institut - Mr John Stone Only', true),
  (NULL, 'FINC310 Financial Markets and Institut - Mr Richard Hauser Only', true),
  (NULL, 'FINC310 Financial Markets and Institut - any instructors Only', true),
  ('FINC312', 'FINC312 Financial Mgt 2 - Dr Lei Wang Only', true),
  (NULL, 'FINC312 Financial Mgt 2 - any instructors Only', true),
  (NULL, 'FINC312 Financial Mgt 2 Financial Mgt 2 - Dr Lei Wang Only', true),
  (NULL, 'FINC312 Financial Mgt 2 Financial Mgt 2 - any instructors Only', true),
  (NULL, 'FINC313 Investments Investments - Mr Richard Hauser Only', true),
  (NULL, 'FINC313 Investments Investments - any instructors Only', true),
  ('FINC318', 'FINC318 Internatl Finan Mgt - Dr Lei Wang Only', true),
  (NULL, 'FINC318 Internatl Finan Mgt - any instructors Only', true),
  ('FINC332', 'FINC332 Intro to Data Analyticsdata Mng  Vislz - Mrs Temidayo Osatuyi Only', true),
  (NULL, 'FINC332 Intro to Data Analyticsdata Mng  Vislz - any instructors Only', true),
  ('FINC420', 'FINC420 Security Analy and Port Mgmt - Mr Richard Hauser Only', true),
  (NULL, 'FINC420 Security Analy and Port Mgmt - any instructors Only', true),
  ('FINC423', 'FINC423 Financial Models - Mr Richard Hauser Only', true),
  (NULL, 'FINC423 Financial Models - any instructors Only', true),
  ('FINC450', 'FINC450 Retirement Estate Plan - Mr Richard Hauser Only', true),
  (NULL, 'FINC450 Retirement Estate Plan - any instructors Only', true),
  
  -- GDPT courses
  ('GDPT802', 'GDPT802 Fnd PathoMed Mgmt 1 - Dr Adriane MacPhedran Only', true),
  (NULL, 'GDPT802 Fnd PathoMed Mgmt 1 - any instructors Only', true),
  ('GDPT810', 'GDPT810 Hlth Care SystPol 1 - Dr Jonathan Ulrich Only', true),
  (NULL, 'GDPT810 Hlth Care SystPol 1 - any instructors Only', true),
  ('GDPT811', 'GDPT811 Applied Anatomy - Dr Donna Skelly Only', true),
  (NULL, 'GDPT811 Applied Anatomy - any instructors Only', true),
  ('GDPT812', 'GDPT812 Fnd in PathoMed Mgmt 2 - Dr Beth Gustafson Only', true),
  (NULL, 'GDPT812 Fnd in PathoMed Mgmt 2 - any instructors Only', true),
  ('GDPT814', 'GDPT814 Evidence-Based Pr 1 - Dr Kristen Snarski Only', true),
  (NULL, 'GDPT814 Evidence-Based Pr 1 - any instructors Only', true),
  ('GDPT815', 'GDPT815 EssentialsPhys Therapy - Dr Adriane MacPhedran Only', true),
  (NULL, 'GDPT815 EssentialsPhys Therapy - any instructors Only', true),
  ('GDPT816', 'GDPT816 Comm Health Initiative 1 - Dr Beth Gustafson Only', true),
  (NULL, 'GDPT816 Comm Health Initiative 1 - any instructors Only', true),
  ('GDPT818', 'GDPT818 Found Human Movement - Dr Carolyn Galleher Only', true),
  (NULL, 'GDPT818 Found Human Movement - any instructors Only', true),
  ('GDPT819', 'GDPT819 Found Human Move Lab - Dr Donna Skelly Only', true),
  (NULL, 'GDPT819 Found Human Move Lab - any instructors Only', true),
  ('GDPT821', 'GDPT821 CardioPulmonary Dysf 1 - Dr Ashley Greenthaner Only', true),
  (NULL, 'GDPT821 CardioPulmonary Dysf 1 - any instructors Only', true),
  ('GDPT822', 'GDPT822 Musculoskeletal Extremt - Dr Carolyn Galleher Only', true),
  (NULL, 'GDPT822 Musculoskeletal Extremt - any instructors Only', true),
  ('GDPT824', 'GDPT824 Musculoskltl Extrem Lab - Dr Carolyn Galleher Only', true),
  (NULL, 'GDPT824 Musculoskltl Extrem Lab - any instructors Only', true),
  ('GDPT825', 'GDPT825 Musculoskeletal Dysf Spine - Dr Donna Skelly Only', true),
  (NULL, 'GDPT825 Musculoskeletal Dysf Spine - any instructors Only', true),
  ('GDPT826', 'GDPT826 Comm Hlth Initiative 2 - Dr Constance Lewis Only', true),
  (NULL, 'GDPT826 Comm Hlth Initiative 2 - any instructors Only', true),
  ('GDPT827', 'GDPT827 Musculoskltl Spine Lab - Dr Carolyn Galleher Only', true),
  (NULL, 'GDPT827 Musculoskltl Spine Lab - any instructors Only', true),
  ('GDPT830', 'GDPT830 Hlth Care Sys  Policy 2 - Dr Jonathan Ulrich Only', true),
  (NULL, 'GDPT830 Hlth Care Sys  Policy 2 - any instructors Only', true),
  ('GDPT831', 'GDPT831 Foundtns In Geriatrics - Dr Constance Lewis Only', true),
  (NULL, 'GDPT831 Foundtns In Geriatrics - any instructors Only', true),
  ('GDPT841', 'GDPT841 Foundations In Pediatrics - Dr Kristen Snarski Only', true),
  (NULL, 'GDPT841 Foundations In Pediatrics - any instructors Only', true),
  (NULL, 'GDPT843 Exam Only', true),
  ('GDPT844', 'GDPT844 Evidence-Based Pr 2 - Dr Kristen Snarski Only', true),
  (NULL, 'GDPT844 Evidence-Based Pr 2 - any instructors Only', true),
  ('GDPT845', 'GDPT845 Neuro Mvmt Dys Lab - Dr Kristen Snarski Only', true),
  (NULL, 'GDPT845 Neuro Mvmt Dys Lab - any instructors Only', true),
  ('GDPT847', 'GDPT847 Clinical Synthesis 1 - Dr Donna Skelly Only', true),
  (NULL, 'GDPT847 Clinical Synthesis 1 - any instructors Only', true),
  ('GDPT848', 'GDPT848 Neuroscience - Mrs Courtney Roca Only', true),
  (NULL, 'GDPT848 Neuroscience - any instructors Only', true),
  ('GDPT849', 'GDPT849 Neuroscience Lab - Mrs Courtney Roca Only', true),
  (NULL, 'GDPT849 Neuroscience Lab - any instructors Only', true),
  
  -- GPHAS courses
  ('GPHAS600', 'GPHAS600 Pre-Rotatn LecSkill Lab - Mrs Natasha Camera Only', true),
  (NULL, 'GPHAS600 Pre-Rotatn LecSkill Lab - any instructors Only', true),
  ('GPHAS601', 'GPHAS601 Pre-Rotatn LecSkill - Mrs Kristen Grippe Only', true),
  (NULL, 'GPHAS601 Pre-Rotatn LecSkill - any instructors Only', true),
  ('GPHAS602', 'GPHAS602 Busn PractCurr Iss PA - Brittney Franley Only', true),
  (NULL, 'GPHAS602 Busn PractCurr Iss PA - any instructors Only', true),
  ('GPHAS616', 'GPHAS616 Clinical Research - Dr Blake Hoppe Only', true),
  (NULL, 'GPHAS616 Clinical Research - any instructors Only', true),
  ('GPHAS619', 'GPHAS619 Fam Med Rotation 3 - Mrs Natasha Camera Only', true),
  (NULL, 'GPHAS619 Fam Med Rotation 3 - any instructors Only', true),
  ('GPHAS623', 'GPHAS623 Elective Rotation 1 - Mrs Natasha Camera Only', true),
  (NULL, 'GPHAS623 Elective Rotation 1 - any instructors Only', true),
  
  -- IE courses
  ('IE201', 'IE201 Engr Proj  Econ - Dr Ikechukwu Ohu Only', true),
  (NULL, 'IE201 Engr Proj  Econ - any instructors Only', true),
  ('IE320', 'IE320 Engineering Stats - Junayed Pasha Only', true),
  (NULL, 'IE320 Engineering Stats - any instructors Only', true),
  ('IE325', 'IE325 Design of Experiments - Dr Ikechukwu Ohu Only', true),
  (NULL, 'IE325 Design of Experiments - any instructors Only', true),
  ('IE350', 'IE350 Operations Research 1 - Junayed Pasha Only', true),
  (NULL, 'IE350 Operations Research 1 - any instructors Only', true),
  
  -- IMGT courses
  ('IMGT375', 'IMGT375 Organizational Internship - Dr Celene Kalivoda Only', true),
  (NULL, 'IMGT375 Organizational Internship - any instructors Only', true),
  ('IMGT420', 'IMGT420 Issues Global Mgmt - Ms Jennifer Karsh Only', true),
  
  -- General/Other
  (NULL, 'INTERVIEW Only', true),
  
  -- MATH courses
  ('MATH103', 'MATH103 Quantitative Literacy - any instructors Only', true),
  ('MATH105', 'MATH105 Fundamentals Math - any instructors Only', true),
  ('MATH111', 'MATH111 College Algebra - Mr Adam Nogaj Only', true),
  (NULL, 'MATH111 College Algebra - Mr Joseph Komorek Only', true),
  (NULL, 'MATH111 College Algebra - any instructors Only', true),
  (NULL, 'MATH111 College Algebra College Algebra - Mr Adam Nogaj Only', true),
  (NULL, 'MATH111 College Algebra College Algebra - any instructors Only', true),
  ('MATH112', 'MATH112 Trigonometry - Mr Joseph Komorek Only', true),
  (NULL, 'MATH112 Trigonometry - Mr Keven Beringer Only', true),
  (NULL, 'MATH112 Trigonometry - Mrs Christine Cedzo Only', true),
  (NULL, 'MATH112 Trigonometry - any instructors Only', true),
  (NULL, 'MATH112 Trigonometry Trigonometry - Mrs Christine Cedzo Only', true),
  (NULL, 'MATH112 Trigonometry Trigonometry - any instructors Only', true),
  ('MATH115', 'MATH115 Applied Math for Business - Dr Richard Ligo Only', true),
  (NULL, 'MATH115 Applied Math for Business - Mr Patrick Chadowski Only', true),
  (NULL, 'MATH115 Applied Math for Business - any instructors Only', true),
  ('MATH140', 'MATH140 Calculus 1 - Dr David Prier Only', true),
  (NULL, 'MATH140 Calculus 1 - Dr Geoffrey Dietz Only', true),
  (NULL, 'MATH140 Calculus 1 - Dr Michael Caulfield Only', true),
  (NULL, 'MATH140 Calculus 1 - Dr Richard Ligo Only', true),
  (NULL, 'MATH140 Calculus 1 - Mr Joseph Komorek Only', true),
  (NULL, 'MATH140 Calculus 1 - Mrs Christine Cedzo Only', true),
  (NULL, 'MATH140 Calculus 1 - any instructors Only', true),
  ('MATH141', 'MATH141 Calculus 2 - Dr David Prier Only', true),
  (NULL, 'MATH141 Calculus 2 - Dr Geoffrey Dietz Only', true),
  (NULL, 'MATH141 Calculus 2 - Dr Michael Caulfield Only', true),
  (NULL, 'MATH141 Calculus 2 - Mrs Christine Cedzo Only', true),
  (NULL, 'MATH141 Calculus 2 - any instructors Only', true),
  ('MATH213', 'MATH213 Applied Statistics - Dr Patrick Headley Only', true),
  (NULL, 'MATH213 Applied Statistics - any instructors Only', true),
  (NULL, 'MATH213 Applied Statistics Applied Statistics - Dr Patrick Headley Only', true),
  (NULL, 'MATH213 Applied Statistics Applied Statistics - Mr Adam Nogaj Only', true),
  (NULL, 'MATH213 Applied Statistics Applied Statistics - any instructors Only', true),
  ('MATH222', 'MATH222 Discrete Math 1 - Dr David Prier Only', true),
  (NULL, 'MATH222 Discrete Math 1 - any instructors Only', true),
  ('MATH223', 'MATH223 Discrete Math 2 - Dr David Prier Only', true),
  (NULL, 'MATH223 Discrete Math 2 - any instructors Only', true),
  ('MATH242', 'MATH242 Calculus 3 - Dr Geoffrey Dietz Only', true),
  (NULL, 'MATH242 Calculus 3 - Dr Michael Caulfield Only', true),
  (NULL, 'MATH242 Calculus 3 - Dr Richard Ligo Only', true),
  (NULL, 'MATH242 Calculus 3 - any instructors Only', true),
  ('MATH243', 'MATH243 Calculus 4 - Dr Richard Ligo Only', true),
  (NULL, 'MATH243 Calculus 4 - any instructors Only', true),
  (NULL, 'MATH304 Diff Equations 1 Diff Equations 1 - Dr Geoffrey Dietz Only', true),
  (NULL, 'MATH304 Diff Equations 1 Diff Equations 1 - any instructors Only', true),
  ('MATH310', 'MATH310 Number TheoryCrypt - Dr David Prier Only', true),
  (NULL, 'MATH310 Number TheoryCrypt - any instructors Only', true),
  ('MATH314', 'MATH314 Numerical Analysis - Dr Geoffrey Dietz Only', true),
  (NULL, 'MATH314 Numerical Analysis - any instructors Only', true),
  
  -- ME courses
  ('ME201', 'ME201 Statics - Dr David Gee Only', true),
  (NULL, 'ME201 Statics - Dr Scott Steinbrink Only', true),
  (NULL, 'ME201 Statics - any instructors Only', true),
  ('ME204', 'ME204 Dynamics - Dr Lokesh Saharan Only', true),
  (NULL, 'ME204 Dynamics - any instructors Only', true),
  ('ME205', 'ME205 Digital Comp Usage - Dr Scott Steinbrink Only', true),
  (NULL, 'ME205 Digital Comp Usage - any instructors Only', true),
  ('ME206', 'ME206 Digital Comp Lab - Dr Scott Steinbrink Only', true),
  (NULL, 'ME206 Digital Comp Lab - any instructors Only', true),
  ('ME207', 'ME207 Engineering Graphics - Dr Lokesh Saharan Only', true),
  (NULL, 'ME207 Engineering Graphics - Mr Dan Arndt Only', true),
  (NULL, 'ME207 Engineering Graphics - any instructors Only', true),
  ('ME208', 'ME208 Comp Graphics Lab - Dr Lokesh Saharan Only', true),
  (NULL, 'ME208 Comp Graphics Lab - Mr Dan Arndt Only', true),
  (NULL, 'ME208 Comp Graphics Lab - any instructors Only', true),
  ('ME214', 'ME214 Strength Materials - Dr Lokesh Saharan Only', true),
  (NULL, 'ME214 Strength Materials - any instructors Only', true),
  ('ME215', 'ME215 Strength Matrl Lab - Dr David Gee Only', true),
  (NULL, 'ME215 Strength Matrl Lab - Dr Scott Steinbrink Only', true),
  (NULL, 'ME215 Strength Matrl Lab - any instructors Only', true),
  (NULL, 'ME312 Engr Thermodynamics Engr Thermodynamics - Dr Hamid Torab Only', true),
  (NULL, 'ME312 Engr Thermodynamics Engr Thermodynamics - any instructors Only', true),
  ('ME315', 'ME315 Materials Science - Dr Paul Flynn Only', true),
  (NULL, 'ME315 Materials Science - Mr Santosh Angadi Only', true),
  (NULL, 'ME315 Materials Science - any instructors Only', true),
  ('ME326', 'ME326 System Dynamics - Dr Lokesh Saharan Only', true),
  (NULL, 'ME326 System Dynamics - any instructors Only', true),
  ('ME329', 'ME329 Materials Process - Dr Robert Michael Only', true),
  (NULL, 'ME329 Materials Process - any instructors Only', true),
  ('ME332', 'ME332 Instr  Measure Lab - Dr Hamid Torab Only', true),
  (NULL, 'ME332 Instr  Measure Lab - any instructors Only', true),
  (NULL, 'ME336 Fluid Mechanics Fluid Mechanics - Dr David Gee Only', true),
  (NULL, 'ME336 Fluid Mechanics Fluid Mechanics - any instructors Only', true),
  ('ME336', 'ME336 Fluid Mechanics - Dr Mahesh Aggarwal Only', true),
  (NULL, 'ME336 Fluid Mechanics - any instructors Only', true),
  (NULL, 'ME337 Heat Transfer Heat Transfer - Dr Hamid Torab Only', true),
  (NULL, 'ME337 Heat Transfer Heat Transfer - any instructors Only', true),
  (NULL, 'ME338 Fluid Mechanics Lab Fluid Mechanics Lab - Dr Hamid Torab Only', true),
  (NULL, 'ME338 Fluid Mechanics Lab Fluid Mechanics Lab - any instructors Only', true),
  ('ME339', 'ME339 Heat Transfer Lab - Dr Hamid Torab Only', true),
  (NULL, 'ME339 Heat Transfer Lab - any instructors Only', true),
  ('ME350', 'ME350 Engineering Design - Dr Robert Michael Only', true),
  (NULL, 'ME350 Engineering Design - any instructors Only', true),
  ('ME360', 'ME360 Machine Design - Bryan Allison Only', true),
  (NULL, 'ME360 Machine Design - any instructors Only', true),
  ('ME411', 'ME411 Alternative Energy Sys - Dr Hamid Torab Only', true),
  (NULL, 'ME411 Alternative Energy Sys - any instructors Only', true),
  ('ME412', 'ME412 Application of CFD - Dr Baiou Shi Only', true),
  (NULL, 'ME412 Application of CFD - any instructors Only', true),
  ('ME440', 'ME440 Advanced Thermodynamics - Dr Hamid Torab Only', true),
  (NULL, 'ME440 Advanced Thermodynamics - any instructors Only', true),
  (NULL, 'ME461 Vibrations Vibrations - Dr Robert Michael Only', true),
  (NULL, 'ME461 Vibrations Vibrations - any instructors Only', true),
  
  -- MGMT courses
  ('MGMT380', 'MGMT380 Executive Leadership - Dr Vishal Arghode Only', true),
  (NULL, 'MGMT380 Executive Leadership - Mr Daniel Zimmerman Only', true),
  (NULL, 'MGMT380 Executive Leadership - any instructors Only', true),
  
  -- MKTG courses
  ('MKTG300', 'MKTG300 Consumer Decision Making - Dr Michael Messina Only', true),
  (NULL, 'MKTG300 Consumer Decision Making - any instructors Only', true),
  ('MKTG330', 'MKTG330 Global Marketing - Mr Timothy Grunzel Only', true),
  (NULL, 'MKTG330 Global Marketing - Mrs Rebecca Russell Only', true),
  (NULL, 'MKTG330 Global Marketing - any instructors Only', true),
  
  -- NURS courses
  ('NURS204', 'NURS204 PharmaNsg Implicatn - Mr Brad Cooper Only', true),
  (NULL, 'NURS204 PharmaNsg Implicatn - any instructors Only', true),
  ('NURS205', 'NURS205 Nursing Prac Comp - Ms Allison DiPlacido Only', true),
  (NULL, 'NURS205 Nursing Prac Comp - Ms Sarah Johnson Only', true),
  (NULL, 'NURS205 Nursing Prac Comp - any instructors Only', true),
  ('NURS206', 'NURS206 Health Assessment 1 - Ms Andrea Chandler Only', true),
  (NULL, 'NURS206 Health Assessment 1 - Ms Jane Riley Only', true),
  (NULL, 'NURS206 Health Assessment 1 - any instructors Only', true),
  ('NURS207', 'NURS207 Health Assessment 2 - Mrs Amber Mecca Only', true),
  (NULL, 'NURS207 Health Assessment 2 - Mrs Kathryn Denison Only', true),
  (NULL, 'NURS207 Health Assessment 2 - any instructors Only', true),
  ('NURS308', 'NURS308 Rsrch Process Nsg - Mrs Amber Mecca Only', true),
  (NULL, 'NURS308 Rsrch Process Nsg - any instructors Only', true),
  ('NURS309', 'NURS309 Influen HlthDisease - Ms Allison DiPlacido Only', true),
  (NULL, 'NURS309 Influen HlthDisease - Ms Catherine Phillips Only', true),
  (NULL, 'NURS309 Influen HlthDisease - any instructors Only', true),
  ('NURS310', 'NURS310 Healthy Childbearing - Mrs Ashton Bird Only', true),
  (NULL, 'NURS310 Healthy Childbearing - any instructors Only', true),
  ('NURS311', 'NURS311 Hlth Rest Older Adlt - Mrs Amber Mecca Only', true),
  (NULL, 'NURS311 Hlth Rest Older Adlt - any instructors Only', true),
  ('NURS320', 'NURS320 Leadership Seminar - Mrs Stephanie McElhaney Only', true),
  (NULL, 'NURS320 Leadership Seminar - any instructors Only', true),
  ('NURS419', 'NURS419 Basic DysrhythmiaEKG - Mrs Jean Bulmer Only', true),
  (NULL, 'NURS419 Basic DysrhythmiaEKG - any instructors Only', true),
  
  -- PHAS courses
  ('PHAS100', 'PHAS100 First-Year Seminar - Mrs Jennifer Majewski Only', true),
  (NULL, 'PHAS100 First-Year Seminar - any instructors Only', true),
  ('PHAS111', 'PHAS111 SemIntro to PA Profession - Mrs Heather Adams Only', true),
  (NULL, 'PHAS111 SemIntro to PA Profession - Mrs Jennifer Majewski Only', true),
  (NULL, 'PHAS111 SemIntro to PA Profession - Shawna Alonge Only', true),
  (NULL, 'PHAS111 SemIntro to PA Profession - any instructors Only', true),
  ('PHAS121', 'PHAS121 Medical Terminology - Dr Angela Eller Only', true),
  (NULL, 'PHAS121 Medical Terminology - Mrs Jennifer Majewski Only', true),
  (NULL, 'PHAS121 Medical Terminology - Mrs Mackenzie Starns Only', true),
  (NULL, 'PHAS121 Medical Terminology - Mrs Natasha Camera Only', true),
  (NULL, 'PHAS121 Medical Terminology - any instructors Only', true),
  ('PHAS215', 'PHAS215 CommResources PatntEnctr - Mrs Kristen Grippe Only', true),
  (NULL, 'PHAS215 CommResources PatntEnctr - any instructors Only', true),
  ('PHAS300', 'PHAS300 Leadership Seminar - Mrs Kristen Grippe Only', true),
  (NULL, 'PHAS300 Leadership Seminar - any instructors Only', true),
  ('PHAS301', 'PHAS301 Professional Ethics  Ldrshp - Dr Blake Hoppe Only', true),
  (NULL, 'PHAS301 Professional Ethics  Ldrshp - any instructors Only', true),
  ('PHAS363', 'PHAS363 Research Process - Mr Dexter Witchey Only', true),
  (NULL, 'PHAS363 Research Process - Ms Kathleen Corello Only', true),
  (NULL, 'PHAS363 Research Process - any instructors Only', true),
  ('PHAS408', 'PHAS408 Behavioral Medicine - Mrs Christina Scanlan Only', true),
  (NULL, 'PHAS408 Behavioral Medicine - any instructors Only', true),
  ('PHAS411', 'PHAS411 Physical Diagonosis 1 - Dr Blake Hoppe Only', true),
  (NULL, 'PHAS411 Physical Diagonosis 1 - any instructors Only', true),
  ('PHAS413', 'PHAS413 Physical Diagnosis 2 - Brittney Franley Only', true),
  (NULL, 'PHAS413 Physical Diagnosis 2 - any instructors Only', true),
  ('PHAS414', 'PHAS414 Med Lecture Series 1 - Mrs Natasha Camera Only', true),
  (NULL, 'PHAS414 Med Lecture Series 1 - any instructors Only', true),
  ('PHAS415', 'PHAS415 Med Lecture Series 2 - Mrs Heather Adams Only', true),
  (NULL, 'PHAS415 Med Lecture Series 2 - any instructors Only', true),
  ('PHAS416', 'PHAS416 Phys Diagnosis 3 - Ms Randie Lugenbeal Only', true),
  (NULL, 'PHAS416 Phys Diagnosis 3 - any instructors Only', true),
  ('PHAS424', 'PHAS424 Pharmacotherapeutics 1 - Dr Charles Fetrow Only', true),
  (NULL, 'PHAS424 Pharmacotherapeutics 1 - any instructors Only', true),
  ('PHAS425', 'PHAS425 Pharmacotherapeu 2 - Dr Charles Fetrow Only', true),
  (NULL, 'PHAS425 Pharmacotherapeu 2 - any instructors Only', true),
  ('PHAS431', 'PHAS431 Clinical Science 1 - Mrs Jennifer Majewski Only', true),
  (NULL, 'PHAS431 Clinical Science 1 - any instructors Only', true),
  ('PHAS432', 'PHAS432 Clinical Science 2 - Mrs Natasha Camera Only', true),
  (NULL, 'PHAS432 Clinical Science 2 - any instructors Only', true),
  ('PHAS438', 'PHAS438 PEDSOBGYN Lect Ser - Mrs Heather Adams Only', true),
  (NULL, 'PHAS438 PEDSOBGYN Lect Ser - any instructors Only', true),
  ('PHAS445', 'PHAS445 Problem Based Med - Mrs Heather Adams Only', true),
  (NULL, 'PHAS445 Problem Based Med - any instructors Only', true),
  
  -- PHYS courses
  ('PHYS101', 'PHYS101 Concepts in Physics - Dr Nicholas Conklin Only', true),
  (NULL, 'PHYS101 Concepts in Physics - any instructors Only', true),
  ('PHYS105', 'PHYS105 College Physics 1 - Mr Perry Hilburn Only', true),
  (NULL, 'PHYS105 College Physics 1 - any instructors Only', true),
  ('PHYS106', 'PHYS106 College Phys Lab 1 - Dr Nicholas Conklin Only', true),
  (NULL, 'PHYS106 College Phys Lab 1 - any instructors Only', true),
  ('PHYS108', 'PHYS108 College Physics 2 - Dr David Horne Only', true),
  (NULL, 'PHYS108 College Physics 2 - Dr Nicholas Conklin Only', true),
  (NULL, 'PHYS108 College Physics 2 - Mr Perry Hilburn Only', true),
  (NULL, 'PHYS108 College Physics 2 - any instructors Only', true),
  ('PHYS109', 'PHYS109 College Phys Lab 2 - Dr Nicholas Conklin Only', true),
  (NULL, 'PHYS109 College Phys Lab 2 - Mr Perry Hilburn Only', true),
  (NULL, 'PHYS109 College Phys Lab 2 - any instructors Only', true),
  ('PHYS210', 'PHYS210 Fund Phys 1 Mechanics - Dr David Horne Only', true),
  (NULL, 'PHYS210 Fund Phys 1 Mechanics - Mr Perry Hilburn Only', true),
  (NULL, 'PHYS210 Fund Phys 1 Mechanics - any instructors Only', true),
  ('PHYS211', 'PHYS211 Fund Phys 1 Lab - Staff Only', true),
  (NULL, 'PHYS211 Fund Phys 1 Lab - any instructors Only', true),
  ('PHYS212', 'PHYS212 Fund Phys 2 FldTherm - Dr David Horne Only', true),
  (NULL, 'PHYS212 Fund Phys 2 FldTherm - any instructors Only', true),
  ('PHYS213', 'PHYS213 Fund Phys 2 Lab - Mr Perry Hilburn Only', true),
  ('PHYS214', 'PHYS214 Fund Phys 3 ElectricityMagnetism - Mr Allen Madura Only', true),
  (NULL, 'PHYS214 Fund Phys 3 ElectricityMagnetism - any instructors Only', true),
  ('PHYS218', 'PHYS218 Gen Phy Lab for Engr - any instructors Only', true),
  
  -- PPRO courses
  ('PPRO391', 'PPRO391 Special Topics - Mrs Melanie Gustafson-Ropski Only', true),
  (NULL, 'PPRO391 Special Topics - any instructors Only', true),
  
  -- PSYC courses
  ('PSYC211', 'PSYC211 Psych Statistics 1 - Dr Jessica Hartnett Only', true),
  (NULL, 'PSYC211 Psych Statistics 1 - Dr John Ranney Only', true),
  (NULL, 'PSYC211 Psych Statistics 1 - Dr Timothy Caswell Only', true),
  (NULL, 'PSYC211 Psych Statistics 1 - any instructors Only', true),
  (NULL, 'PSYC211 Psych Statistics 1 Psych Statistics 1 - Dr Jessica Hartnett Only', true),
  (NULL, 'PSYC211 Psych Statistics 1 Psych Statistics 1 - Dr John Ranney Only', true),
  (NULL, 'PSYC211 Psych Statistics 1 Psych Statistics 1 - Dr Timothy Caswell Only', true),
  (NULL, 'PSYC211 Psych Statistics 1 Psych Statistics 1 - any instructors Only', true),
  
  -- RADS courses
  ('RADS441', 'RADS441 Intro To Radiology - Gail Schroeder Only', true),
  (NULL, 'RADS441 Intro To Radiology - any instructors Only', true),
  
  -- SPRT courses
  ('SPRT130', 'SPRT130 Nutr Sprt  Exercise - Dr Suzanne Kitts Only', true),
  (NULL, 'SPRT130 Nutr Sprt  Exercise - any instructors Only', true),
  ('SPRT240', 'SPRT240 Sprt PsycThry  Appl - Dr Jason Willow Only', true),
  (NULL, 'SPRT240 Sprt PsycThry  Appl - any instructors Only', true),
  ('SPRT250', 'SPRT250 Psyc AspctsExerPhys Act - Dr Jason Willow Only', true),
  (NULL, 'SPRT250 Psyc AspctsExerPhys Act - any instructors Only', true),
  ('SPRT270', 'SPRT270 Personal Training - Mrs Jenna Rappold Only', true),
  (NULL, 'SPRT270 Personal Training - any instructors Only', true),
  ('SPRT310', 'SPRT310 Rsch Meth Exercise Sci - Ms Kara Kern Only', true),
  (NULL, 'SPRT310 Rsch Meth Exercise Sci - any instructors Only', true),
  ('SPRT360', 'SPRT360 Kinesiology - Dr Kory Stauffer Only', true),
  (NULL, 'SPRT360 Kinesiology - Ms Elizabeth Miller Only', true),
  (NULL, 'SPRT360 Kinesiology - any instructors Only', true),
  ('SPRT361', 'SPRT361 Kinesiology Lab - Dr Suzanne Kitts Only', true),
  (NULL, 'SPRT361 Kinesiology Lab - any instructors Only', true),
  ('SPRT385', 'SPRT385 Psyc of Injury and Rehab - Dr Jason Willow Only', true),
  (NULL, 'SPRT385 Psyc of Injury and Rehab - any instructors Only', true),
  ('SPRT390', 'SPRT390 Physiology Exrc Sprt - Dr Kory Stauffer Only', true),
  (NULL, 'SPRT390 Physiology Exrc Sprt - any instructors Only', true),
  ('SPRT391', 'SPRT391 Physio Exrc Sprt Lab - Mrs Jenna Rappold Only', true),
  (NULL, 'SPRT391 Physio Exrc Sprt Lab - Ms Kara Kern Only', true),
  (NULL, 'SPRT391 Physio Exrc Sprt Lab - any instructors Only', true),
  ('SPRT400', 'SPRT400 Ftn Assess Exrc Presc - Ms Kara Kern Only', true),
  (NULL, 'SPRT400 Ftn Assess Exrc Presc - any instructors Only', true),
  ('SPRT401', 'SPRT401 Fitness Assess Lab - Mrs Jenna Rappold Only', true),
  (NULL, 'SPRT401 Fitness Assess Lab - any instructors Only', true),
  
  -- Other/General
  (NULL, 'Visual Body Software Only', true),
  (NULL, 'EvalInter Neuro Mvt Dys - Dr Beth Gustafson Only', true),
  (NULL, 'EvalInter Neuro Mvt Dys - any instructors Only', true)
ON CONFLICT (course_code) DO UPDATE SET
  course_name = EXCLUDED.course_name,
  active = EXCLUDED.active,
  updated_at = NOW();

-- Note: Entries with NULL course_code will be inserted as new rows since course_code is UNIQUE
-- This allows multiple focus options for the same course code (e.g., different instructors)
