-- GU courses seed (generated by scripts/seed-gu-academics.js)
INSERT INTO courses (course_code, course_name, active)
VALUES
  ('ACCT_313', 'Accounting Information Systems', true),
  ('ACCT_315', 'Intermediate Fin Accounting II', true),
  ('MATH_140', 'Calculus 1', true),
  ('MATH_141', 'Calculus 2', true)
ON CONFLICT (course_code) DO UPDATE SET
  course_name = EXCLUDED.course_name,
  active = EXCLUDED.active,
  updated_at = NOW();
